<Project>
	<PropertyGroup>
		<Product>Mega Man 2 Randomizer</Product>
		<Authors>Duckfist, Squidman, Dagit, Charlieboy, Quantam</Authors>

		<PackageTags></PackageTags>
		<PackageReleaseNotes></PackageReleaseNotes>
		<PackageProjectUrl>https://github.com/squid-man/MegaMan2Randomizer2</PackageProjectUrl>

		<RepositoryUrl>https://github.com/squid-man/MegaMan2Randomizer2</RepositoryUrl>

		<DefaultTargetFramework>net10.0-browser</DefaultTargetFramework>
		<LangVersion>latest</LangVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
	</PropertyGroup>
	
	<Target Name="CustomAssemblyVersioning" AfterTargets="MinVer">
		<PropertyGroup>
			<GitHeight>0</GitHeight>
			<GitHeight Condition="'$(MinVerPreRelease)' != ''">$(MinVerPreRelease.Substring($(MinVerPreRelease.LastIndexOf('.'))).TrimStart('.'))</GitHeight>
			<MinVerPatch Condition="'$(MinVerPreRelease)' == ''">0</MinVerPatch>
			<MinVerPatchMinusOne>$([MSBuild]::Subtract($(MinVerPatch), 1))</MinVerPatchMinusOne>
			<MinVerPatchMinusOne Condition="$(MinVerPatchMinusOne) &lt; 0">0</MinVerPatchMinusOne>
			<AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatchMinusOne).$(GitHeight)</AssemblyVersion>
			<FileVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatchMinusOne).$(GitHeight)</FileVersion>
		</PropertyGroup>
	</Target>
</Project>