namespace MM2Randomizer
{
    public enum PlayerSprite
    {
        MegaMan,
        AVGN,
        Bass,
        BassReloaded,
        BreakMan,
        CasualTom,
        Charlieboy,
        CutMansBadScissorsDay,
        FinalFantasyFighter,
        HatsuneMiku,
        JustinBailey,
        Link,
        LuckyMan,
        LuigiArcade,
        MarioArcade,
        MegaManX,
        MegaRan2Remix,
        NewLands,
        ProtoMan,
        PrototypeTom,
        QuickMan,
        Quint,
        Remix,
        Roll,
        Samus,
        VineMan,
    }
}
