namespace MM2Randomizer.Enums
{
    public enum EMusicID
    {
        Flash       = 0x00,
        Wood        = 0x01,
        Crash       = 0x02,
        Heat        = 0x03,
        Air         = 0x04,
        Metal       = 0x05,
        Quick       = 0x06,
        Bubble      = 0x07,
        Wily1       = 0x08,
        Wily3       = 0x09,
        StageSelected = 0x0B,
        Boss        = 0x0B,
        StageSelect = 0x0C,
        Title       = 0x0D,
        Intro       = 0x0E,
        GameOver    = 0x0F,
        Password    = 0x10,
        WilyCastle  = 0x11,
        WilyCapsule = 0x12,
        Ending      = 0x13,
        Credits     = 0x14,
        StageClear  = 0x15,
        GameClear   = 0x16,
        GetItem     = 0x17,
        Wily2       = 0x18,
        Wily4       = 0x19,
        Wily5       = 0x1A,
        Wily6       = 0x1B,
        Nothing     = 0xFF,
    }
}
