<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <WasmRuntimeAssetsLocation>./_framework</WasmRuntimeAssetsLocation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
      
    <!-- Disable compression for now since GitHub Pages doesn't support it -->
    <CompressionEnabled>false</CompressionEnabled>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Browser" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="js65.browser" Version="1.0.7" GeneratePathProperty="true" />
    <PackageReference Include="js65.interop" Version="1.0.7" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RandomizerHost\RandomizerHost.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <WasmExtraFilesToDeploy Include="wwwroot\**" />
  </ItemGroup>
  
  <Target Name="CopyJs65Assets" AfterTargets="ResolvePackageAssets">
    <ItemGroup>
      <Js65Files Include="$(Pkgjs65_browser)\assets\js65\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(Js65Files)" DestinationFolder="$(MSBuildProjectDirectory)\wwwroot\js65\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
  
  <PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
  </PropertyGroup>
  
  <!-- These aren't needed for partial trim mode, but they'll be useful hints in getting full mode working -->
  <ItemGroup>
    <TrimmerRootAssembly Include="CommunityToolkit.Mvvm" />
    <TrimmerRootAssembly Include="js65.browser" />
    <TrimmerRootAssembly Include="js65.interop" />
    <TrimmerRootAssembly Include="MsBox.Avalonia" />
    <TrimmerRootAssembly Include="Microsoft.Extensions.DependencyInjection" />
    <TrimmerRootAssembly Include="Newtonsoft.Json" />
    <TrimmerRootAssembly Include="System.IO.Hashing" />
    <TrimmerRootAssembly Include="System.Security.Cryptography" />
  </ItemGroup>
</Project>
