//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BossSpriteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BossSpriteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.BossSpriteResources", typeof(BossSpriteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirMan_Another {
            get {
                object obj = ResourceManager.GetObject("AirMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("AirMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("AirMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Airman_HornetMan {
            get {
                object obj = ResourceManager.GetObject("Airman_HornetMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("AirMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Airman_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("Airman_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Airman_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("Airman_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_Cray {
            get {
                object obj = ResourceManager.GetObject("Alien_Cray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("Alien_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_Exhaust {
            get {
                object obj = ResourceManager.GetObject("Alien_Exhaust", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_Grayzone {
            get {
                object obj = ResourceManager.GetObject("Alien_Grayzone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_Gyotot {
            get {
                object obj = ResourceManager.GetObject("Alien_Gyotot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("Alien_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("Alien_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alien_RockMan2Hardcore {
            get {
                object obj = ResourceManager.GetObject("Alien_RockMan2Hardcore", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoobeamTrap_MegaMan1TurretV1 {
            get {
                object obj = ResourceManager.GetObject("BoobeamTrap_MegaMan1TurretV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoobeamTrap_MegaMan1TurretV2 {
            get {
                object obj = ResourceManager.GetObject("BoobeamTrap_MegaMan1TurretV2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoobeamTrap_MegaMan5Turret {
            get {
                object obj = ResourceManager.GetObject("BoobeamTrap_MegaMan5Turret", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_April {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_April", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_BurgerTime {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_BurgerTime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_CapnA {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_CapnA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Charlieboy {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Charlieboy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Don {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Don", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_DoubleDragon {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_DoubleDragon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_DrCossack {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_DrCossack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_DrLight {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_DrLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Leo {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Leo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_LilMac {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_LilMac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_MegaMan4Squid {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_MegaMan4Squid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Mikey {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Mikey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_MortalKombat {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_MortalKombat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_MrX {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_MrX", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_NoReset {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_NoReset", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_NothinButSpeedruns {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_NothinButSpeedruns", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_PizzaHut {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_PizzaHut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Raph {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Raph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Shredder {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Shredder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_SiberianBull {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_SiberianBull", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_SpeedGaming {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_SpeedGaming", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_Squidman {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_Squidman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoorSign_WWF {
            get {
                object obj = ResourceManager.GetObject("BossDoorSign_WWF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_Another {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("BubbleMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_Another {
            get {
                object obj = ResourceManager.GetObject("CrashMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("CrashMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_DX {
            get {
                object obj = ResourceManager.GetObject("CrashMan_DX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("CrashMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("CrashMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("CrashMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("CrashMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlashMan_Another {
            get {
                object obj = ResourceManager.GetObject("FlashMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlashMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("FlashMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlashMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("FlashMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlashMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("FlashMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlashMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("FlashMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlashMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("FlashMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GutsTank_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("GutsTank_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GutsTank_Cray
        {
            get
            {
                object obj = ResourceManager.GetObject("GutsTank_Cray", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_Another {
            get {
                object obj = ResourceManager.GetObject("HeatMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("HeatMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_DX {
            get {
                object obj = ResourceManager.GetObject("HeatMan_DX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("HeatMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("HeatMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("HeatMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeatMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("HeatMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MechaDragon_CoolDraga {
            get {
                object obj = ResourceManager.GetObject("MechaDragon_CoolDraga", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MechaDragon_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("MechaDragon_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MechaDragon_Dragocorn {
            get {
                object obj = ResourceManager.GetObject("MechaDragon_Dragocorn", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MechaDragon_Shades {
            get {
                object obj = ResourceManager.GetObject("MechaDragon_Shades", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MechaDragon_Swag {
            get {
                object obj = ResourceManager.GetObject("MechaDragon_Swag", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("MetalMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalMan_ElecMan {
            get {
                object obj = ResourceManager.GetObject("MetalMan_ElecMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("MetalMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("MetalMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("MetalMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("MetalMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PicopicoKun_CheatMode {
            get {
                object obj = ResourceManager.GetObject("PicopicoKun_CheatMode", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PicopicoKun_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("PicopicoKun_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PicopicoKun_VineMan {
            get {
                object obj = ResourceManager.GetObject("PicopicoKun_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_Another {
            get {
                object obj = ResourceManager.GetObject("QuickMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("QuickMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("QuickMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("QuickMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("QuickMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("QuickMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickMan_Sonic {
            get {
                object obj = ResourceManager.GetObject("QuickMan_Sonic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_Abobo {
            get {
                object obj = ResourceManager.GetObject("Wily_Abobo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_Cossack {
            get {
                object obj = ResourceManager.GetObject("Wily_Cossack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("Wily_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_DrLight {
            get {
                object obj = ResourceManager.GetObject("Wily_DrLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_DrM {
            get {
                object obj = ResourceManager.GetObject("Wily_DrM", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_MegaMan3 {
            get {
                object obj = ResourceManager.GetObject("Wily_MegaMan3", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wily_RiverCityMan {
            get {
                object obj = ResourceManager.GetObject("Wily_RiverCityMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_Another {
            get {
                object obj = ResourceManager.GetObject("WoodMan_Another", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("WoodMan_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_DK {
            get {
                object obj = ResourceManager.GetObject("WoodMan_DK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_DX {
            get {
                object obj = ResourceManager.GetObject("WoodMan_DX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_GrayZone {
            get {
                object obj = ResourceManager.GetObject("WoodMan_GrayZone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_Peercast {
            get {
                object obj = ResourceManager.GetObject("WoodMan_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("WoodMan_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_RockMan2Plus {
            get {
                object obj = ResourceManager.GetObject("WoodMan_RockMan2Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WoodMan_ToadMan {
            get {
                object obj = ResourceManager.GetObject("WoodMan_ToadMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
