//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnemySpriteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnemySpriteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.EnemySpriteResources", typeof(EnemySpriteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Batton_Ghost {
            get {
                object obj = ResourceManager.GetObject("Batton_Ghost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Batton_Vader {
            get {
                object obj = ResourceManager.GetObject("Batton_Vader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Blocky_Rocky {
            get {
                object obj = ResourceManager.GetObject("Blocky_Rocky", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Blocky_TotemPolen {
            get {
                object obj = ResourceManager.GetObject("Blocky_TotemPolen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ChangkeyMaker_ConstructionJoe {
            get {
                object obj = ResourceManager.GetObject("ChangkeyMaker_ConstructionJoe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Claw_Chiko {
            get {
                object obj = ResourceManager.GetObject("Claw_Chiko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Claw_MarioFish {
            get {
                object obj = ResourceManager.GetObject("Claw_MarioFish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Claw_Peercast {
            get {
                object obj = ResourceManager.GetObject("Claw_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlyBoy_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("FlyBoy_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlyBoy_VineMan {
            get {
                object obj = ResourceManager.GetObject("FlyBoy_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ForceBeamBody_Block {
            get {
                object obj = ResourceManager.GetObject("ForceBeamBody_Block", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ForceBeamBody_Invisible {
            get {
                object obj = ResourceManager.GetObject("ForceBeamBody_Invisible", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ForceBeamEnd_Invisible {
            get {
                object obj = ResourceManager.GetObject("ForceBeamEnd_Invisible", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ForceBeamEnd_NyanCat {
            get {
                object obj = ResourceManager.GetObject("ForceBeamEnd_NyanCat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Friender_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("Friender_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Friender_Evil {
            get {
                object obj = ResourceManager.GetObject("Friender_Evil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KaminariGoro_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("KaminariGoro_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KaminariGoro_MetLord {
            get {
                object obj = ResourceManager.GetObject("KaminariGoro_MetLord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KerogAndPetitKerog_Hearts {
            get {
                object obj = ResourceManager.GetObject("KerogAndPetitKerog_Hearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KerogAndPetitKerog_Komasaburo {
            get {
                object obj = ResourceManager.GetObject("KerogAndPetitKerog_Komasaburo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KerogAndPetitKerog_MetMom {
            get {
                object obj = ResourceManager.GetObject("KerogAndPetitKerog_MetMom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kukku_DX {
            get {
                object obj = ResourceManager.GetObject("Kukku_DX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kukku_VineCock {
            get {
                object obj = ResourceManager.GetObject("Kukku_VineCock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M445_M422A {
            get {
                object obj = ResourceManager.GetObject("M445_M422A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M445_Metroid {
            get {
                object obj = ResourceManager.GetObject("M445_Metroid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Matasaburo_EnhancedBlow {
            get {
                object obj = ResourceManager.GetObject("Matasaburo_EnhancedBlow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mole_MegaMan9Drill {
            get {
                object obj = ResourceManager.GetObject("Mole_MegaMan9Drill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Monking_VineMan {
            get {
                object obj = ResourceManager.GetObject("Monking_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NeoMetall_1UpMet1 {
            get {
                object obj = ResourceManager.GetObject("NeoMetall_1UpMet1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NeoMetall_1UpMet2 {
            get {
                object obj = ResourceManager.GetObject("NeoMetall_1UpMet2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pierobot_VineMan {
            get {
                object obj = ResourceManager.GetObject("Pierobot_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PipiAndCopipi_Beat {
            get {
                object obj = ResourceManager.GetObject("PipiAndCopipi_Beat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PipiAndCopipi_BomberPipi {
            get {
                object obj = ResourceManager.GetObject("PipiAndCopipi_BomberPipi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PipiAndCopipi_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("PipiAndCopipi_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PipiAndCopipi_NotTheBees {
            get {
                object obj = ResourceManager.GetObject("PipiAndCopipi_NotTheBees", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Press_Crusher2 {
            get {
                object obj = ResourceManager.GetObject("Press_Crusher2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Press_FlatCrusher {
            get {
                object obj = ResourceManager.GetObject("Press_FlatCrusher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Robbit_MegaMan1Joe {
            get {
                object obj = ResourceManager.GetObject("Robbit_MegaMan1Joe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Robbit_MetalManRabbit {
            get {
                object obj = ResourceManager.GetObject("Robbit_MetalManRabbit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Robbit_Shrek {
            get {
                object obj = ResourceManager.GetObject("Robbit_Shrek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Robbit_Turtle {
            get {
                object obj = ResourceManager.GetObject("Robbit_Turtle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scworm_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("Scworm_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scworm_FlameThrow {
            get {
                object obj = ResourceManager.GetObject("Scworm_FlameThrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shotman_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("Shotman_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shotman_Turret {
            get {
                object obj = ResourceManager.GetObject("Shotman_Turret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shrink_MegaMan1Watcher {
            get {
                object obj = ResourceManager.GetObject("Shrink_MegaMan1Watcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shrink_Metall {
            get {
                object obj = ResourceManager.GetObject("Shrink_Metall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperJoeAndSniperArmor_MegaMan1ContructionJoe {
            get {
                object obj = ResourceManager.GetObject("SniperJoeAndSniperArmor_MegaMan1ContructionJoe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperJoeAndSniperArmor_ProtoJoe {
            get {
                object obj = ResourceManager.GetObject("SniperJoeAndSniperArmor_ProtoJoe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperJoeAndSniperArmor_ProtoJoeAndMech {
            get {
                object obj = ResourceManager.GetObject("SniperJoeAndSniperArmor_ProtoJoeAndMech", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperJoeAndSniperArmor_SniperMet {
            get {
                object obj = ResourceManager.GetObject("SniperJoeAndSniperArmor_SniperMet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SniperJoeAndSniperArmor_SpecialJoe {
            get {
                object obj = ResourceManager.GetObject("SniperJoeAndSniperArmor_SpecialJoe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Springer_BMSpringer {
            get {
                object obj = ResourceManager.GetObject("Springer_BMSpringer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Springer_CuteSpringer {
            get {
                object obj = ResourceManager.GetObject("Springer_CuteSpringer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Springer_MegaMan6Springer {
            get {
                object obj = ResourceManager.GetObject("Springer_MegaMan6Springer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Springer_Saw {
            get {
                object obj = ResourceManager.GetObject("Springer_Saw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tanishi_HatCrab {
            get {
                object obj = ResourceManager.GetObject("Tanishi_HatCrab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tanishi_MetCrab {
            get {
                object obj = ResourceManager.GetObject("Tanishi_MetCrab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Telly_EyeTelly {
            get {
                object obj = ResourceManager.GetObject("Telly_EyeTelly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Telly_Telly2 {
            get {
                object obj = ResourceManager.GetObject("Telly_Telly2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
