//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvironmentSpriteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvironmentSpriteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.EnvironmentSpriteResources", typeof(EnvironmentSpriteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_MegaMan5MiniCastle {
            get {
                object obj = ResourceManager.GetObject("Castle_MegaMan5MiniCastle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_None {
            get {
                object obj = ResourceManager.GetObject("Castle_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_OnlyHills {
            get {
                object obj = ResourceManager.GetObject("Castle_OnlyHills", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_ProtoMan {
            get {
                object obj = ResourceManager.GetObject("Castle_ProtoMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_What {
            get {
                object obj = ResourceManager.GetObject("Castle_What", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_DoctorMarioV1 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_DoctorMarioV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_DoctorMarioV2 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_DoctorMarioV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3V2 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3V3 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3V4 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBrosBrick {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBrosBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Ash {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Ash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Charlieboy {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Charlieboy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Cloud {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Cloud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_DoctorMarioPill {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_DoctorMarioPill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_DoctorMarioVirus {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_DoctorMarioVirus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Note {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Note", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_NyanCat {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_NyanCat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Question {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Question", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_SuperMarioBros2V1 {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_SuperMarioBros2V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_SuperMarioBros2V2 {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_SuperMarioBros2V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_SuperMarioBrosBrick {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_SuperMarioBrosBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_WB {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_WB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_1UP {
            get {
                object obj = ResourceManager.GetObject("Spikes_1UP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Ash {
            get {
                object obj = ResourceManager.GetObject("Spikes_Ash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Diamond {
            get {
                object obj = ResourceManager.GetObject("Spikes_Diamond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_DIE {
            get {
                object obj = ResourceManager.GetObject("Spikes_DIE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("Spikes_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Jelectro {
            get {
                object obj = ResourceManager.GetObject("Spikes_Jelectro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MarioStar {
            get {
                object obj = ResourceManager.GetObject("Spikes_MarioStar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V2 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V3 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V4 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan4V1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan4V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan4V2 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan4V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan4V3 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan4V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Muncher {
            get {
                object obj = ResourceManager.GetObject("Spikes_Muncher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_SkullV1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_SkullV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_SkullV2 {
            get {
                object obj = ResourceManager.GetObject("Spikes_SkullV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
