//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvironmentSpriteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvironmentSpriteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.EnvironmentSpriteResources", typeof(EnvironmentSpriteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoors_CB {
            get {
                object obj = ResourceManager.GetObject("BossDoors_CB", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoors_CB2 {
            get {
                object obj = ResourceManager.GetObject("BossDoors_CB2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoors_DD {
            get {
                object obj = ResourceManager.GetObject("BossDoors_DD", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoors_DK {
            get {
                object obj = ResourceManager.GetObject("BossDoors_DK", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossDoors_Link {
            get {
                object obj = ResourceManager.GetObject("BossDoors_Link", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_DoctorMarioV1 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_DoctorMarioV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_DoctorMarioV2 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_DoctorMarioV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3V2 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3V3 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBros3V4 {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBros3V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestructibleBlock_SuperMarioBrosBrick {
            get {
                object obj = ResourceManager.GetObject("DestructibleBlock_SuperMarioBrosBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Ash {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Ash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Charlieboy {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Charlieboy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Cloud {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Cloud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_DoctorMarioPill {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_DoctorMarioPill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_DoctorMarioVirus {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_DoctorMarioVirus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Note {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Note", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_NyanCat {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_NyanCat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_Question {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_Question", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_SuperMarioBros2V1 {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_SuperMarioBros2V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_SuperMarioBros2V2 {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_SuperMarioBros2V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_SuperMarioBrosBrick {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_SuperMarioBrosBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragonBlock_WB {
            get {
                object obj = ResourceManager.GetObject("DragonBlock_WB", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_CB {
            get {
                object obj = ResourceManager.GetObject("Ladders_CB", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan1 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan1", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan1_2 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }


        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan3 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan3", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan4 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan4", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan4_2 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan5 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan5", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_MegaMan6 {
            get {
                object obj = ResourceManager.GetObject("Ladders_MegaMan6", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ladders_Vine {
            get {
                object obj = ResourceManager.GetObject("Ladders_Vine", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_1UP {
            get {
                object obj = ResourceManager.GetObject("Spikes_1UP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Ash {
            get {
                object obj = ResourceManager.GetObject("Spikes_Ash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Diamond {
            get {
                object obj = ResourceManager.GetObject("Spikes_Diamond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_DIE {
            get {
                object obj = ResourceManager.GetObject("Spikes_DIE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("Spikes_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Jelectro {
            get {
                object obj = ResourceManager.GetObject("Spikes_Jelectro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MarioStar {
            get {
                object obj = ResourceManager.GetObject("Spikes_MarioStar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V2 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V3 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan3V4 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan3V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan4V1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan4V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan4V2 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan4V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_MegaMan4V3 {
            get {
                object obj = ResourceManager.GetObject("Spikes_MegaMan4V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_Muncher {
            get {
                object obj = ResourceManager.GetObject("Spikes_Muncher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_SkullV1 {
            get {
                object obj = ResourceManager.GetObject("Spikes_SkullV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spikes_SkullV2 {
            get {
                object obj = ResourceManager.GetObject("Spikes_SkullV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_AirMan_Block_Clear {
            get {
                object obj = ResourceManager.GetObject("StageTile_AirMan_Block_Clear", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_AirMan_Goblin_CutmanBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("StageTile_AirMan_Goblin_CutmanBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_AirMan_Goblin_Platform {
            get {
                object obj = ResourceManager.GetObject("StageTile_AirMan_Goblin_Platform", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_CBv1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_CBv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_CBv2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_CBv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_CoinfallV1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_CoinfallV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_CoinfallV2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_CoinfallV2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_FinalFantasy {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_FinalFantasy", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_None {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_QBlock {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_QBlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_Rain {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_Rain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_Sand {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_Sand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_BubbleMan_Waterfall_SuperMarioBros2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_BubbleMan_Waterfall_SuperMarioBros2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_Block_SuperMarioBrosBlock {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_Block_SuperMarioBrosBlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_Block_SuperMarioBrosBrick {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_Block_SuperMarioBrosBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_Block_TMNT2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_Block_TMNT2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_DaylightBackground_SuperMarioBrosClouds {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_DaylightBackground_SuperMarioBrosClouds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_Globe_TMNT2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_Globe_TMNT2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_NightBackground_SuperMarioBros3Stars {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_NightBackground_SuperMarioBros3Stars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_CrashMan_Pipe_SuperMarioBros {
            get {
                object obj = ResourceManager.GetObject("StageTile_CrashMan_Pipe_SuperMarioBros", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_FlashMan_Background_DDBrick {
            get {
                object obj = ResourceManager.GetObject("StageTile_FlashMan_Background_DDBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_FlashMan_Background_FinalMix {
            get {
                object obj = ResourceManager.GetObject("StageTile_FlashMan_Background_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_FlashMan_Background_Guard {
            get {
                object obj = ResourceManager.GetObject("StageTile_FlashMan_Background_Guard", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_FlashMan_Block_SuperMarioBrosBlock {
            get {
                object obj = ResourceManager.GetObject("StageTile_FlashMan_Block_SuperMarioBrosBlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Background_None {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Background_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Block_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Block_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_Axe {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_Axe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_CBv1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_CBv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_CBv2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_CBv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_Sand {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_Sand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_SpikeV1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_SpikeV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_SpikeV2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_SpikeV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_SuperMarioBros {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_SuperMarioBros", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_HeatMan_Lava_TMNT2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_HeatMan_Lava_TMNT2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Background_CutmansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Background_CutmansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Background_None {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Background_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Block_Sand {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Block_Sand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Conveyor_CB {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Conveyor_CB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Conveyor_CB2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Conveyor_CB2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Conveyor_CB3 {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Conveyor_CB3", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_MetalMan_Conveyor_CutmansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("StageTile_MetalMan_Conveyor_CutmansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_QuickMan_Background_None {
            get {
                object obj = ResourceManager.GetObject("StageTile_QuickMan_Background_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_QuickMan_Block_HeatBrick {
            get {
                object obj = ResourceManager.GetObject("StageTile_QuickMan_Block_HeatBrick", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily1_Climb_Checkered {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily1_Climb_Checkered", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily1_Climb_DDBricks {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily1_Climb_DDBricks", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily1_Floor_Checkered {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily1_Floor_Checkered", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily1_Floor_DDBricks {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily1_Floor_DDBricks", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_Animated_CutmansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_Animated_CutmansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_Animated_CutmansBadScissorsDay2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_Animated_CutmansBadScissorsDay2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_Animated_WilyTV {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_Animated_WilyTV", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_4_Floor_Waffle {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_4_Floor_Waffle", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_4_Floor_Pico {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_4_Floor_Pico", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_4_Background_AdventureIsland {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_4_Background_AdventureIsland", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily2_4_Background_Snake {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily2_4_Background_Snake", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Background_Cog {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Background_Cog", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Background_DarkRoom
        {
            get
            {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Background_DarkRoom", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan1", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan1_2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan1_3 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }


        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan3 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan3", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan4 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan4", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan4_2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan5 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan5", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_Wily5_Teleporter_MegaMan6 {
            get {
                object obj = ResourceManager.GetObject("StageTile_Wily5_Teleporter_MegaMan6", resourceCulture);
                return ((byte[])(obj));
            }
        }



        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Block_SuperMarioBros {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Block_SuperMarioBros", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_CaveBackground_None {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_CaveBackground_None", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_CaveGround_FinalFantasy {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_CaveGround_FinalFantasy", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_CaveGround_Sand {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_CaveGround_Sand", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Grass_FinalFantasy {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Grass_FinalFantasy", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Grass_SuperMarioBros2V1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Grass_SuperMarioBros2V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Grass_SuperMarioBros2V2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Grass_SuperMarioBros2V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Grass_SuperMarioBros3V1 {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Grass_SuperMarioBros3V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Grass_SuperMarioBros3V2 {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Grass_SuperMarioBros3V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageTile_WoodMan_Grass_SuperMarioBros3V3 {
            get {
                object obj = ResourceManager.GetObject("StageTile_WoodMan_Grass_SuperMarioBros3V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
