//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenusAndTransitionScreenRandomizer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenusAndTransitionScreenRandomizer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.MenusAndTransitionScreenRandomizer", typeof(MenusAndTransitionScreenRandomizer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_FinalFantasy {
            get {
                object obj = ResourceManager.GetObject("Castle_FinalFantasy", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_MegaMan5MiniCastle {
            get {
                object obj = ResourceManager.GetObject("Castle_MegaMan5MiniCastle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_None {
            get {
                object obj = ResourceManager.GetObject("Castle_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_OnlyHills {
            get {
                object obj = ResourceManager.GetObject("Castle_OnlyHills", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_ProtoMan {
            get {
                object obj = ResourceManager.GetObject("Castle_ProtoMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Castle_What {
            get {
                object obj = ResourceManager.GetObject("Castle_What", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RobotMasterIntroScreen_Background1 {
            get {
                object obj = ResourceManager.GetObject("RobotMasterIntroScreen_Background1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RobotMasterIntroScreen_Background2 {
            get {
                object obj = ResourceManager.GetObject("RobotMasterIntroScreen_Background2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageSelectScreen_BasicMaster {
            get {
                object obj = ResourceManager.GetObject("StageSelectScreen_BasicMaster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageSelectScreen_Claw {
            get {
                object obj = ResourceManager.GetObject("StageSelectScreen_Claw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageSelectScreen_Exile {
            get {
                object obj = ResourceManager.GetObject("StageSelectScreen_Exile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageSelectScreen_FinalMix {
            get {
                object obj = ResourceManager.GetObject("StageSelectScreen_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageSelectScreen_None {
            get {
                object obj = ResourceManager.GetObject("StageSelectScreen_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageSelectScreen_Ultra {
            get {
                object obj = ResourceManager.GetObject("StageSelectScreen_Ultra", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponGetScreen_Claw {
            get {
                object obj = ResourceManager.GetObject("WeaponGetScreen_Claw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponGetScreen_FinalMix {
            get {
                object obj = ResourceManager.GetObject("WeaponGetScreen_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponGetScreen_MissingTile {
            get {
                object obj = ResourceManager.GetObject("WeaponGetScreen_MissingTile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponGetScreen_None {
            get {
                object obj = ResourceManager.GetObject("WeaponGetScreen_None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponGetScreen_Remix {
            get {
                object obj = ResourceManager.GetObject("WeaponGetScreen_Remix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponGetScreen_Ultra {
            get {
                object obj = ResourceManager.GetObject("WeaponGetScreen_Ultra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_Battletoads {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_Battletoads", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_CB {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_CB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_DestructibleBlock {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_DestructibleBlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_Kirby {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_Kirby", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_MegaMan {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_MegaMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_MegaManX {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_MegaManX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_Pacman {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_Pacman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_Paperboy {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_Paperboy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_SmallRefill1 {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_SmallRefill1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_SmallRefill2 {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_SmallRefill2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_SmallRefill3 {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_SmallRefill3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_ZeldaCandle {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_ZeldaCandle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeaponMenuBorder_ZeldaShield {
            get {
                object obj = ResourceManager.GetObject("WeaponMenuBorder_ZeldaShield", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
