//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerCharacterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerCharacterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.PlayerCharacterResources", typeof(PlayerCharacterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_AVGN {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_AVGN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Bass {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Bass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_BassReloaded {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_BassReloaded", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_BatMan {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_BatMan", resourceCulture);
                return ((byte[])(obj));
            }
        }


        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_BreakMan {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_BreakMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Byte {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Byte", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_ByteRed {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_ByteRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_CasualTom {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_CasualTom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Charlieboy {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Charlieboy", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_CharlieboyAlt {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_CharlieboyAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_CutMansBadScissorsDayBlue {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_CutMansBadScissorsDayBlue", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_FinalFantasyBlackBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("PlayerCharacter_FinalFantasyBlackBelt", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_FinalFantasyBlackMage
        {
            get
            {
                object obj = ResourceManager.GetObject("PlayerCharacter_FinalFantasyBlackMage", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_FinalFantasyFighter {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_FinalFantasyFighter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_FinalFantasyFighterBlue {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_FinalFantasyFighterBlue", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_FinalFantasyWhiteMage {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_FinalFantasyWhiteMage", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Guard {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Guard", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_HatsuneMiku {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_HatsuneMiku", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_JustinBailey {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_JustinBailey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Link {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Link", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_LuckyMan {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_LuckyMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_LuigiArcade {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_LuigiArcade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_MarioArcade {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_MarioArcade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_MegaManX {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_MegaManX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_MegaMari {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_MegaMari", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_MegaRan2Remix {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_MegaRan2Remix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_NewLands {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_NewLands", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_ProtoMan {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_ProtoMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_PrototypeTom {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_PrototypeTom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_QuickMan {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_QuickMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Quint {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Quint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Remix {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Remix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Rock {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Rock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Roll {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Roll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_RollFromMegaMan8 {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_RollFromMegaMan8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_Samus {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_Samus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayerCharacter_VineMan {
            get {
                object obj = ResourceManager.GetObject("PlayerCharacter_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
