//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Also randomize the &quot;Dr. WILY&quot;?
        ///# DR. COSSACK
        ///# DR. LIGHT
        ///# MR. X
        ///# BREAK MAN
        ///# DOC ROBOT
        ///# BASS
        ///#
        ///# Misc
        ///CLASH
        ///WILY
        ///PROTO
        ///BREAK
        ///ROCK
        ///DARK
        ///ENKER
        ///QUINT
        ///PUNK
        ///BALLADE
        ///#
        ///# Mega Man
        ///CUT
        ///ELEC
        ///ICE
        ///FIRE
        ///BOMB
        ///GUTS
        ///#
        ///# Mega Man 2
        ///BUBBLE
        ///HEAT
        ///METAL
        ///AIR
        ///FLASH
        ///QUICK
        ///WOOD
        ///CRASH
        ///#
        ///# MEGA MAN 3
        ///TOP
        ///GEMINI
        ///SHADOW
        ///NEEDLE
        ///HARD
        ///MAGNET
        ///SNAKE
        ///SPARK
        ///#
        ///# MEGA MAN 4
        ///PHARAOH
        ///BRIGHT
        ///RING
        ///DUST
        ///SKULL
        ///DIVE
        ///DRILL
        ///TOAD
        ///#
        ///# MEGA MAN 5
        ///STAR
        ///GRAVITY
        ///GYRO
        ///CRYSTAL
        ///NAPALM
        ///STONE
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bossnames {
            get {
                return ResourceManager.GetString("bossnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;!--
        ///Name must not exceed 13 characters
        ///--&gt;
        ///&lt;CompanyNameSet&gt;
        ///    &lt;!-- # --&gt;
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;0verflow&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;1up Studio&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;2K Games&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;3D Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompanyNameConfig {
            get {
                return ResourceManager.GetString("CompanyNameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;!--
        ///Prefix must not exceed 3 characters
        ///Name must not exceed 25 characters
        ///--&gt;
        ///&lt;CountryNameSet&gt;
        ///    &lt;!--
        ///    Real Countries
        ///    --&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;AFGHANISTAN&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;ALBANIA&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;ALGERIA&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryNameConfig {
            get {
                return ResourceManager.GetString("CountryNameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;CreditTextSet&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Value&gt;09&lt;/Value&gt;
        ///        &lt;Text&gt;MM2 RANDOMIZER&lt;/Text&gt;
        ///    &lt;/CreditText&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Value&gt;2A&lt;/Value&gt;
        ///        &lt;Text&gt;ROBOT MASTERS&lt;/Text&gt;
        ///    &lt;/CreditText&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Value&gt;61&lt;/Value&gt;
        ///        &lt;Text&gt;`&lt;/Text&gt;
        ///    &lt;/CreditText&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreditTextConfig {
            get {
                return ResourceManager.GetString("CreditTextConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;IntroStorySet&gt;
        ///    &lt;!-- Test --&gt;
        ///    &lt;IntroStory&gt;
        ///        &lt;Enabled&gt;false&lt;/Enabled&gt;
        ///        &lt;Title&gt;Test&lt;/Title&gt;
        ///        &lt;Lines&gt;
        ///            &lt;Line&gt;`1234567890-=&lt;/Line&gt;
        ///            &lt;Line&gt;~!@#$%^&amp;amp;*()_+&lt;/Line&gt;
        ///            &lt;Line&gt;qwertyuiop[]\&lt;/Line&gt;
        ///            &lt;Line&gt;QWERTYUIOP{}|&lt;/Line&gt;
        ///            &lt;Line&gt;asdfghjkl;&apos;&lt;/Line&gt;
        ///            &lt;Line&gt;ASDFGHJKL:&quot;&lt;/Line&gt;
        ///            &lt;Line&gt;zxcvbnm,./&lt;/Line&gt;
        ///            &lt;Line&gt;ZXCVBNM&amp;lt;&amp;gt;?&lt;/Line&gt;
        ///            &lt;Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntroStoryConfig {
            get {
                return ResourceManager.GetString("IntroStoryConfig", resourceCulture);
            }
        }
    }
}
