//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeaponSpriteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeaponSpriteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.WeaponSpriteResources", typeof(WeaponSpriteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirShooter_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("AirShooter_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirShooter_FinalMix {
            get {
                object obj = ResourceManager.GetObject("AirShooter_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirShooter_GodWorld {
            get {
                object obj = ResourceManager.GetObject("AirShooter_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirShooter_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("AirShooter_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirShooter_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("AirShooter_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AirShooter_VineMan {
            get {
                object obj = ResourceManager.GetObject("AirShooter_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AtomicFire_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("AtomicFire_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AtomicFire_FinalMix {
            get {
                object obj = ResourceManager.GetObject("AtomicFire_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AtomicFire_GodWorld {
            get {
                object obj = ResourceManager.GetObject("AtomicFire_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AtomicFire_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("AtomicFire_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AtomicFire_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("AtomicFire_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_GodWorld {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_SearchSnakeV1 {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_SearchSnakeV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_SearchSnakeV2 {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_SearchSnakeV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BubbleLead_SparkShock {
            get {
                object obj = ResourceManager.GetObject("BubbleLead_SparkShock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashBomber_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("CrashBomber_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashBomber_FinalMix {
            get {
                object obj = ResourceManager.GetObject("CrashBomber_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashBomber_GodWorld {
            get {
                object obj = ResourceManager.GetObject("CrashBomber_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashBomber_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("CrashBomber_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashBomber_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("CrashBomber_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrashBomber_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("CrashBomber_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item1_MegaMan2Remix {
            get {
                object obj = ResourceManager.GetObject("Item1_MegaMan2Remix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item1_MetCarrier {
            get {
                object obj = ResourceManager.GetObject("Item1_MetCarrier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item1_Peercast {
            get {
                object obj = ResourceManager.GetObject("Item1_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item1_Rollchan2 {
            get {
                object obj = ResourceManager.GetObject("Item1_Rollchan2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_BulletBill {
            get {
                object obj = ResourceManager.GetObject("Item2_BulletBill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_CutMansBadScissorsDay {
            get {
                object obj = ResourceManager.GetObject("Item2_CutMansBadScissorsDay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_MegaMan2Remix {
            get {
                object obj = ResourceManager.GetObject("Item2_MegaMan2Remix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_Peercast {
            get {
                object obj = ResourceManager.GetObject("Item2_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_RedSuperArrow {
            get {
                object obj = ResourceManager.GetObject("Item2_RedSuperArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_Rollchan2Broom {
            get {
                object obj = ResourceManager.GetObject("Item2_Rollchan2Broom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_RushJet1 {
            get {
                object obj = ResourceManager.GetObject("Item2_RushJet1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item2_RushJet2 {
            get {
                object obj = ResourceManager.GetObject("Item2_RushJet2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item3_MegaMan2Remix {
            get {
                object obj = ResourceManager.GetObject("Item3_MegaMan2Remix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item3_Met {
            get {
                object obj = ResourceManager.GetObject("Item3_Met", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item3_Peercast {
            get {
                object obj = ResourceManager.GetObject("Item3_Peercast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Item3_Rollchan2 {
            get {
                object obj = ResourceManager.GetObject("Item3_Rollchan2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_FinalMix {
            get {
                object obj = ResourceManager.GetObject("LeafShield_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_GodWorld {
            get {
                object obj = ResourceManager.GetObject("LeafShield_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("LeafShield_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_JewelSatelliteV1 {
            get {
                object obj = ResourceManager.GetObject("LeafShield_JewelSatelliteV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_JewelSatelliteV2 {
            get {
                object obj = ResourceManager.GetObject("LeafShield_JewelSatelliteV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("LeafShield_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("LeafShield_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LeafShield_SkullBarrier {
            get {
                object obj = ResourceManager.GetObject("LeafShield_SkullBarrier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_FinalMix {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_GodWorld {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_HypnoShot {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_HypnoShot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_ShadowBlade {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_ShadowBlade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetalBlade_Star {
            get {
                object obj = ResourceManager.GetObject("MetalBlade_Star", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_FinalMix {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_FinalMix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_GodWorld {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_GodWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_RockMan2E {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_RockMan2E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuickBoomerang_VineMan {
            get {
                object obj = ResourceManager.GetObject("QuickBoomerang_VineMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TimeStopper_DeusExMachina {
            get {
                object obj = ResourceManager.GetObject("TimeStopper_DeusExMachina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TimeStopper_JavaIslandIndonesia {
            get {
                object obj = ResourceManager.GetObject("TimeStopper_JavaIslandIndonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TimeStopper_MegaMan5FlashStopper {
            get {
                object obj = ResourceManager.GetObject("TimeStopper_MegaMan5FlashStopper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TimeStopper_NoConstancy {
            get {
                object obj = ResourceManager.GetObject("TimeStopper_NoConstancy", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
