name: Release Official Build

on:
  push:
    branches:
      - master
      - main
      - develop
      - ava-update4
      
    tags:
      - '*'
      - '!*dev*'
      
jobs:
  build:
    uses: ./.github/workflows/build-core.yml
    with:
      target-folder: .
      is-official: true
        